##WebhookのURLを記入してください
URL: 

##送信する際に名前とチャットで送信する場合はtrueを記入してください
##プレイヤーのネームタグとチャットで送信する場合はfalseを記入してください
名前だけで送信する: false

##サーバー開放時に送信するメッセージを記入してください
サーバー開放: サーバーを開放しました

##サーバー閉鎖時に送信するメッセージを記入してください
サーバー閉鎖: サーバーを閉鎖しました 
